from __future__ import annotations

import json
import shutil
from pathlib import Path
from typing import Any, Sequence

from kogwistar.engine_core.engine import GraphKnowledgeEngine
from kogwistar.engine_core.models import Grounding, Span
from kogwistar.runtime import MappingStepResolver, WorkflowRuntime
from kogwistar.runtime.design import load_workflow_design
from kogwistar.runtime.models import (
    RunSuccess,
    WorkflowDesignArtifact,
    WorkflowEdge,
    WorkflowInvocationRequest,
    WorkflowNode,
)


class _DemoEmbeddingFunction:
    _name = "nested-workflow-demo-embedding-v1"

    def name(self):
        return self._name

    def __call__(self, input: Sequence[str]) -> list[list[float]]:
        vectors: list[list[float]] = []
        for text in input:
            length = float((len(str(text or "")) % 13) + 1)
            checksum = float(sum(ord(ch) for ch in str(text or "")) % 17)
            vectors.append([length, checksum or 1.0])
        return vectors


def _grounding(doc_id: str) -> Grounding:
    return Grounding(spans=[Span.from_dummy_for_workflow(doc_id)])


def _workflow_node(
    *,
    workflow_id: str,
    node_id: str,
    op: str,
    start: bool = False,
    terminal: bool = False,
) -> WorkflowNode:
    return WorkflowNode(
        id=node_id,
        label=node_id.split("|")[-1],
        type="entity",
        doc_id=node_id,
        summary=op,
        properties={},
        metadata={
            "entity_type": "workflow_node",
            "workflow_id": workflow_id,
            "wf_op": op,
            "wf_start": bool(start),
            "wf_terminal": bool(terminal),
            "wf_version": "v_demo",
        },
        mentions=[_grounding(f"wf:{workflow_id}")],
        level_from_root=0,
        domain_id=None,
        canonical_entity_id=None,
        embedding=None,
    )


def _workflow_edge(
    *,
    workflow_id: str,
    edge_id: str,
    src: str,
    dst: str,
    is_default: bool = True,
) -> WorkflowEdge:
    return WorkflowEdge(
        id=edge_id,
        label="wf_next",
        type="relationship",
        doc_id=edge_id,
        summary="next",
        properties={},
        source_ids=[src],
        target_ids=[dst],
        source_edge_ids=[],
        target_edge_ids=[],
        relation="wf_next",
        metadata={
            "entity_type": "workflow_edge",
            "workflow_id": workflow_id,
            "wf_priority": 100,
            "wf_is_default": bool(is_default),
            "wf_multiplicity": "one",
            "wf_version": "v_demo",
        },
        mentions=[_grounding(f"wf:{workflow_id}")],
        domain_id=None,
        canonical_entity_id=None,
        embedding=None,
    )


def _build_design_from_rows(
    *,
    workflow_id: str,
    rows: dict[str, Any],
) -> WorkflowDesignArtifact:
    nodes = [
        _workflow_node(
            workflow_id=workflow_id,
            node_id=item["node_id"],
            op=item["op"],
            start=bool(item.get("start", False)),
            terminal=bool(item.get("terminal", False)),
        )
        for item in list(rows.get("nodes") or [])
    ]
    edges = [
        _workflow_edge(
            workflow_id=workflow_id,
            edge_id=item["edge_id"],
            src=item["src"],
            dst=item["dst"],
            is_default=bool(item.get("is_default", True)),
        )
        for item in list(rows.get("edges") or [])
    ]
    start_node_id = next(node.id for node in nodes if bool(node.metadata.get("wf_start")))
    return WorkflowDesignArtifact(
        workflow_id=workflow_id,
        workflow_version="v_demo",
        start_node_id=start_node_id,
        nodes=nodes,
        edges=edges,
        notes=str(rows.get("notes") or ""),
    )


PREDEFINED_DYNAMIC_BLUEPRINT: dict[str, Any] = {
    "notes": "Pretend this was generated by a planner LLM, but keep it deterministic.",
    "nodes": [
        {
            "node_id": "wf|demo.child.dynamic|start",
            "op": "start",
            "start": True,
        },
        {
            "node_id": "wf|demo.child.dynamic|materialize",
            "op": "dynamic_materialize",
        },
        {
            "node_id": "wf|demo.child.dynamic|end",
            "op": "end",
            "terminal": True,
        },
    ],
    "edges": [
        {
            "edge_id": "wf|demo.child.dynamic|e|start->materialize",
            "src": "wf|demo.child.dynamic|start",
            "dst": "wf|demo.child.dynamic|materialize",
        },
        {
            "edge_id": "wf|demo.child.dynamic|e|materialize->end",
            "src": "wf|demo.child.dynamic|materialize",
            "dst": "wf|demo.child.dynamic|end",
        },
    ],
}


def _persist_design(
    workflow_engine: GraphKnowledgeEngine,
    *,
    workflow_id: str,
    nodes: list[WorkflowNode],
    edges: list[WorkflowEdge],
) -> None:
    _ = workflow_id
    for node in nodes:
        workflow_engine.write.add_node(node)
    for edge in edges:
        workflow_engine.write.add_edge(edge)


def _build_engines(
    *,
    data_dir: Path,
    backend_factory: Any | None = None,
) -> tuple[GraphKnowledgeEngine, GraphKnowledgeEngine]:
    embedding = _DemoEmbeddingFunction()
    kwargs: dict[str, Any] = {
        "embedding_function": embedding,
    }
    if backend_factory is not None:
        kwargs["backend_factory"] = backend_factory
    workflow_engine = GraphKnowledgeEngine(
        persist_directory=str(data_dir / "workflow"),
        kg_graph_type="workflow",
        **kwargs,
    )
    conversation_engine = GraphKnowledgeEngine(
        persist_directory=str(data_dir / "conversation"),
        kg_graph_type="conversation",
        **kwargs,
    )
    return workflow_engine, conversation_engine


def run_nested_workflow_invocation_demo(
    *,
    data_dir: str | Path | None = None,
    reset_data: bool = True,
    backend_factory: Any | None = None,
    workflow_engine: GraphKnowledgeEngine | None = None,
    conversation_engine: GraphKnowledgeEngine | None = None,
) -> dict[str, Any]:
    """Golden example for predesigned and dynamically persisted sub-workflows."""

    if (workflow_engine is None) != (conversation_engine is None):
        raise ValueError(
            "workflow_engine and conversation_engine must be provided together"
        )

    if workflow_engine is None or conversation_engine is None:
        root = (
            Path(data_dir)
            if data_dir is not None
            else Path(".gke-data/nested-workflow-demo")
        )
        if reset_data and root.exists():
            shutil.rmtree(root)
        root.mkdir(parents=True, exist_ok=True)

        workflow_engine, conversation_engine = _build_engines(
            data_dir=root, backend_factory=backend_factory
        )
    else:
        if data_dir is not None:
            root = Path(data_dir)
        else:
            workflow_root = Path(str(getattr(workflow_engine, "persist_directory", ".")))
            conversation_root = Path(
                str(getattr(conversation_engine, "persist_directory", "."))
            )
            root = workflow_root.parent
            if conversation_root.parent != root:
                root = workflow_root

    parent_workflow_id = "demo.parent"
    predesigned_workflow_id = "demo.child.predesigned"
    dynamic_workflow_id = "demo.child.dynamic"
    conversation_id = "demo-conv-nested-workflows"
    turn_node_id = "demo-turn-nested-workflows"
    run_id = "demo-run-nested-workflows"

    parent_nodes = [
        _workflow_node(
            workflow_id=parent_workflow_id,
            node_id="wf|demo.parent|start",
            op="start",
            start=True,
        ),
        _workflow_node(
            workflow_id=parent_workflow_id,
            node_id="wf|demo.parent|invoke_predesigned",
            op="invoke_predesigned",
        ),
        _workflow_node(
            workflow_id=parent_workflow_id,
            node_id="wf|demo.parent|invoke_dynamic",
            op="invoke_dynamic",
        ),
        _workflow_node(
            workflow_id=parent_workflow_id,
            node_id="wf|demo.parent|end",
            op="end",
            terminal=True,
        ),
    ]
    parent_edges = [
        _workflow_edge(
            workflow_id=parent_workflow_id,
            edge_id="wf|demo.parent|e|start->invoke_predesigned",
            src="wf|demo.parent|start",
            dst="wf|demo.parent|invoke_predesigned",
        ),
        _workflow_edge(
            workflow_id=parent_workflow_id,
            edge_id="wf|demo.parent|e|invoke_predesigned->invoke_dynamic",
            src="wf|demo.parent|invoke_predesigned",
            dst="wf|demo.parent|invoke_dynamic",
        ),
        _workflow_edge(
            workflow_id=parent_workflow_id,
            edge_id="wf|demo.parent|e|invoke_dynamic->end",
            src="wf|demo.parent|invoke_dynamic",
            dst="wf|demo.parent|end",
        ),
    ]
    _persist_design(
        workflow_engine,
        workflow_id=parent_workflow_id,
        nodes=parent_nodes,
        edges=parent_edges,
    )

    predesigned_nodes = [
        _workflow_node(
            workflow_id=predesigned_workflow_id,
            node_id="wf|demo.child.predesigned|start",
            op="start",
            start=True,
        ),
        _workflow_node(
            workflow_id=predesigned_workflow_id,
            node_id="wf|demo.child.predesigned|body",
            op="predesigned_body",
        ),
        _workflow_node(
            workflow_id=predesigned_workflow_id,
            node_id="wf|demo.child.predesigned|end",
            op="end",
            terminal=True,
        ),
    ]
    predesigned_edges = [
        _workflow_edge(
            workflow_id=predesigned_workflow_id,
            edge_id="wf|demo.child.predesigned|e|start->body",
            src="wf|demo.child.predesigned|start",
            dst="wf|demo.child.predesigned|body",
        ),
        _workflow_edge(
            workflow_id=predesigned_workflow_id,
            edge_id="wf|demo.child.predesigned|e|body->end",
            src="wf|demo.child.predesigned|body",
            dst="wf|demo.child.predesigned|end",
        ),
    ]
    _persist_design(
        workflow_engine,
        workflow_id=predesigned_workflow_id,
        nodes=predesigned_nodes,
        edges=predesigned_edges,
    )

    dynamic_design = _build_design_from_rows(
        workflow_id=dynamic_workflow_id,
        rows=PREDEFINED_DYNAMIC_BLUEPRINT,
    )

    resolver = MappingStepResolver()

    @resolver.register("start")
    def _start(ctx):
        return RunSuccess(
            conversation_node_id=None,
            state_update=[
                (
                    "u",
                    {
                        "golden_example": "nested_workflow_invocation",
                        "planner_payload": json.loads(
                            json.dumps(PREDEFINED_DYNAMIC_BLUEPRINT)
                        ),
                    },
                )
            ],
            _route_next=["invoke_predesigned"],
        )

    @resolver.register("invoke_predesigned")
    def _invoke_predesigned(ctx):
        return RunSuccess(
            conversation_node_id=None,
            state_update=[("u", {"predesigned_requested": True})],
            workflow_invocations=[
                WorkflowInvocationRequest(
                    workflow_id=predesigned_workflow_id,
                    result_state_key="predesigned_child",
                )
            ],
            _route_next=["invoke_dynamic"],
        )

    @resolver.register("invoke_dynamic")
    def _invoke_dynamic(ctx):
        planner_payload = dict(ctx.state_view.get("planner_payload") or {})
        return RunSuccess(
            conversation_node_id=None,
            state_update=[
                (
                    "u",
                    {
                        "dynamic_requested": True,
                        "dynamic_planner_payload_hash": json.dumps(
                            planner_payload, sort_keys=True
                        ),
                    },
                )
            ],
            workflow_invocations=[
                WorkflowInvocationRequest(
                    workflow_id=dynamic_workflow_id,
                    workflow_design=dynamic_design,
                    result_state_key="dynamic_child",
                )
            ],
            _route_next=["end"],
        )

    @resolver.register("predesigned_body")
    def _predesigned_body(ctx):
        return RunSuccess(
            conversation_node_id=None,
            state_update=[
                (
                    "u",
                    {
                        "child_mode": "predesigned",
                        "child_note": "loaded from workflow engine by workflow_id",
                    },
                )
            ],
        )

    @resolver.register("dynamic_materialize")
    def _dynamic_materialize(ctx):
        planner_payload = dict(ctx.state_view.get("planner_payload") or {})
        return RunSuccess(
            conversation_node_id=None,
            state_update=[
                (
                    "u",
                    {
                        "child_mode": "dynamic_persisted",
                        "child_note": str(
                            planner_payload.get("notes")
                            or "planner payload persisted into workflow graph"
                        ),
                    },
                )
            ],
        )

    @resolver.register("end")
    def _end(ctx):
        return RunSuccess(
            conversation_node_id=None,
            state_update=[("u", {"completed": True})],
        )

    runtime = WorkflowRuntime(
        workflow_engine=workflow_engine,
        conversation_engine=conversation_engine,
        step_resolver=resolver,
        predicate_registry={},
        checkpoint_every_n_steps=1,
        max_workers=4,
    )
    result = runtime.run(
        workflow_id=parent_workflow_id,
        conversation_id=conversation_id,
        turn_node_id=turn_node_id,
        initial_state={"_deps": {}},
        run_id=run_id,
    )

    predesigned_child_run_id = str(
        result.final_state.get("predesigned_child__run_id") or ""
    )
    dynamic_child_run_id = str(result.final_state.get("dynamic_child__run_id") or "")

    def _workflow_shape(workflow_id: str) -> dict[str, Any]:
        start, nodes, adj, _rev_adj = load_workflow_design(
            workflow_engine=workflow_engine, workflow_id=workflow_id
        )
        return {
            "start_node_id": start.id,
            "node_ids": sorted(nodes.keys()),
            "edge_ids": sorted(
                edge.id for edges in adj.values() for edge in list(edges or [])
            ),
        }

    def _step_execs(run_id_value: str) -> list[Any]:
        nodes = conversation_engine.read.get_nodes(
            where={"$and": [{"entity_type": "workflow_step_exec"}, {"run_id": run_id_value}]},
            limit=10_000,
        )
        return sorted(
            list(nodes or []),
            key=lambda node: int((getattr(node, "metadata", {}) or {}).get("step_seq", -1)),
        )

    def _workflow_runs(run_id_value: str) -> list[Any]:
        return conversation_engine.read.get_nodes(
            where={"$and": [{"entity_type": "workflow_run"}, {"run_id": run_id_value}]},
            limit=10_000,
        )

    parent_steps = _step_execs(run_id)
    predesigned_steps = _step_execs(predesigned_child_run_id)
    dynamic_steps = _step_execs(dynamic_child_run_id)

    return {
        "summary": {
            "status": result.status,
            "data_dir": str(root),
            "parent_workflow_id": parent_workflow_id,
            "predesigned_workflow_id": predesigned_workflow_id,
            "dynamic_workflow_id": dynamic_workflow_id,
            "predesigned_child_run_id": predesigned_child_run_id,
            "dynamic_child_run_id": dynamic_child_run_id,
            "workflow_graphs_visible": {
                "parent": True,
                "predesigned_child": True,
                "dynamic_child": True,
            },
            "conversation_trace_counts": {
                "parent_steps": len(parent_steps),
                "predesigned_child_steps": len(predesigned_steps),
                "dynamic_child_steps": len(dynamic_steps),
            },
        },
        "details": {
            "final_state": dict(result.final_state),
            "workflow_shapes": {
                "parent": _workflow_shape(parent_workflow_id),
                "predesigned_child": _workflow_shape(predesigned_workflow_id),
                "dynamic_child": _workflow_shape(dynamic_workflow_id),
            },
            "conversation_trace": {
                "parent_run_nodes": [node.id for node in _workflow_runs(run_id)],
                "predesigned_child_run_nodes": [
                    node.id for node in _workflow_runs(predesigned_child_run_id)
                ],
                "dynamic_child_run_nodes": [
                    node.id for node in _workflow_runs(dynamic_child_run_id)
                ],
                "parent_step_ops": [
                    str((getattr(node, "metadata", {}) or {}).get("op") or "")
                    for node in parent_steps
                ],
                "predesigned_child_step_ops": [
                    str((getattr(node, "metadata", {}) or {}).get("op") or "")
                    for node in predesigned_steps
                ],
                "dynamic_child_step_ops": [
                    str((getattr(node, "metadata", {}) or {}).get("op") or "")
                    for node in dynamic_steps
                ],
            },
            "planner_payload": json.loads(json.dumps(PREDEFINED_DYNAMIC_BLUEPRINT)),
        },
    }


if __name__ == "__main__":
    print(
        json.dumps(
            run_nested_workflow_invocation_demo(),
            indent=2,
            ensure_ascii=False,
            default=str,
        )
    )
