"""Thin agent composition contracts built on Kogwistar primitives.

This package does not contain another workflow engine.  It provides typed
profile, provider, catalog, and deterministic skill-ingestion helpers which
delegate execution to the existing workflow runtime.
"""

from .catalog import (
    CatalogEntry,
    CatalogGroup,
    CatalogSearchResult,
    CatalogSemanticRanker,
    CatalogStore,
    DurableCatalogStore,
)
from .compression import (
    CompressionDecision,
    CompressionPolicy,
    CompressionRequest,
    CompressionResult,
    build_compression_request,
    build_compression_workflow,
    persist_summary_projection,
    policy_for,
    select_for_compression,
    should_request_compression,
)
from .context import ContextPolicy, ContextSnapshot
from .delegation import (
    DelegationSpec,
    bounded_child_result,
    build_delegated_invocation,
    delegated_initial_state,
    make_delegation_handler,
)
from .harness import AgentHarness, AsyncAgentHarness
from .bindings import (
    FunctionFakeTool,
    SequenceFakeModel,
    dynamic_invocation,
    make_nested_invocation_handler,
    register_catalog_search_step,
    register_model_step,
    register_tool_step,
    static_invocation,
    validate_invocation_request,
)
from .control import (
    ControlPointSpec,
    ControlPolicy,
    register_control_ack_step,
    register_control_point,
    terminalize_control_messages,
)
from .limits import AgentBudgetPolicy, budget_hints, refresh_budget_hints
from .hooks import HookEffect, HookFailureMode, HookRegistry, HookResult, HookSpec
from .wisdom import (
    BestEffortDistiller,
    DistillationRequest,
    DistillationResult,
    compile_approved_proposal_to_skill,
    record_skill_use_observation,
)
from .profile import AgentProfile
from .plugins import (
    FilesystemSkillProvider,
    LlmWikiIngestionAdapter,
    McpDiscoveryProvider,
    ProjectGlossaryProvider,
    ProjectPluginManifest,
    ingest_project_glossary_to_knowledge,
    ingest_filesystem_skill,
    materialize_skill_artifact,
    make_skill_projection_cleanup,
    mark_inferred_edges_as_candidates,
    deduplicate_inferred_edges,
    select_mcp_schemas,
)
from .providers import (
    CompressorProvider,
    ProviderCollisionError,
    ProviderIdentity,
    ProviderInactiveError,
    ProviderOwnershipError,
    ProviderRegistry,
    ProviderRegistration,
    PROVIDER_LIFECYCLE_NAMESPACE,
    DiscoveryProvider,
    MemoryProvider,
    ModelProvider,
    SkillProvider,
    ToolProvider,
    normalize_descriptor,
)
from .read_tools import AgentReadTools, ReadPage, ReadScope
from .skills import (
    SkillGraphArtifact,
    SkillGraphEdge,
    SkillGraphNode,
    SkillExecutionPlan,
    SkillExecutionEvidence,
    SkillExecutionPolicy,
    SkillProjectionRequest,
    SkillStepKind,
    SemanticSkillIngestionProvider,
    SkillProjectionStore,
    DurableSkillProjectionStore,
    DurableSkillCatalogMaterializer,
    AsyncDurableSkillCatalogMaterializer,
    attach_glossary_references,
    catalog_entries_from_artifact,
    parse_skill_text,
    select_skill_subgraph,
    prepare_skill_execution,
    build_skill_execution_evidence,
    validate_skill_artifact,
    validate_command_argv,
    validate_package_relative_path,
)
from .workflows import (
    build_goal_workflow,
    build_normal_workflow,
    build_plan_workflow,
    graph_signature,
    validate_agent_design,
    validate_control_point_placement,
    without_agent_mode_metadata,
)

__all__ = [
    "AgentHarness",
    "AgentProfile",
    "AsyncAgentHarness",
    "AgentBudgetPolicy",
    "CatalogEntry",
    "CatalogGroup",
    "CatalogSearchResult",
    "CatalogSemanticRanker",
    "CatalogStore",
    "CompressionDecision",
    "CompressionPolicy",
    "CompressionRequest",
    "CompressionResult",
    "ContextPolicy",
    "ContextSnapshot",
    "DelegationSpec",
    "DiscoveryProvider",
    "ModelProvider",
    "ToolProvider",
    "SkillProvider",
    "MemoryProvider",
    "CompressorProvider",
    "HookEffect",
    "HookFailureMode",
    "HookRegistry",
    "HookResult",
    "HookSpec",
    "BestEffortDistiller",
    "DistillationRequest",
    "DistillationResult",
    "ProviderIdentity",
    "ProviderInactiveError",
    "ProviderCollisionError",
    "ProviderOwnershipError",
    "ProviderRegistry",
    "ProviderRegistration",
    "PROVIDER_LIFECYCLE_NAMESPACE",
    "normalize_descriptor",
    "AgentReadTools",
    "FilesystemSkillProvider",
    "LlmWikiIngestionAdapter",
    "McpDiscoveryProvider",
    "ProjectGlossaryProvider",
    "ProjectPluginManifest",
    "ingest_project_glossary_to_knowledge",
    "ingest_filesystem_skill",
    "materialize_skill_artifact",
    "make_skill_projection_cleanup",
    "mark_inferred_edges_as_candidates",
    "deduplicate_inferred_edges",
    "select_mcp_schemas",
    "ControlPointSpec",
    "ControlPolicy",
    "FunctionFakeTool",
    "ReadPage",
    "ReadScope",
    "SequenceFakeModel",
    "SkillGraphArtifact",
    "SkillGraphEdge",
    "SkillGraphNode",
    "SkillExecutionPlan",
    "SkillExecutionEvidence",
    "SkillExecutionPolicy",
    "SkillProjectionRequest",
    "SkillStepKind",
    "SemanticSkillIngestionProvider",
    "SkillProjectionStore",
    "DurableCatalogStore",
    "DurableSkillProjectionStore",
    "DurableSkillCatalogMaterializer",
    "AsyncDurableSkillCatalogMaterializer",
    "attach_glossary_references",
    "catalog_entries_from_artifact",
    "parse_skill_text",
    "select_skill_subgraph",
    "prepare_skill_execution",
    "build_skill_execution_evidence",
    "should_request_compression",
    "validate_skill_artifact",
    "validate_command_argv",
    "validate_package_relative_path",
    "build_goal_workflow",
    "build_normal_workflow",
    "build_plan_workflow",
    "budget_hints",
    "dynamic_invocation",
    "bounded_child_result",
    "build_delegated_invocation",
    "delegated_initial_state",
    "graph_signature",
    "validate_agent_design",
    "validate_control_point_placement",
    "make_nested_invocation_handler",
    "make_delegation_handler",
    "refresh_budget_hints",
    "register_catalog_search_step",
    "register_control_ack_step",
    "register_control_point",
    "register_model_step",
    "register_tool_step",
    "static_invocation",
    "validate_invocation_request",
    "terminalize_control_messages",
    "without_agent_mode_metadata",
    "build_compression_request",
    "build_compression_workflow",
    "persist_summary_projection",
    "policy_for",
    "select_for_compression",
    "compile_approved_proposal_to_skill",
    "record_skill_use_observation",
]
