from __future__ import annotations

"""
Storage backend abstraction.

Goal: remove direct Chroma collection usage from engine.py so we can later plug in
a Postgres+pgvector backend with the same surface.

This backend is intentionally "thin": it mostly forwards calls to underlying
stores. Semantics live in engine/runtime, not in the backend.

Key design points:
- Methods accept **kwargs and forward to the underlying backend implementation.
- Chroma backend supports the same collection set the engine uses today:
  node_index, nodes, edges, edge_endpoints, documents, domains, node_docs,
  node_refs, edge_refs.
- UnitOfWork exists so engine/runtime can write `with engine.uow(): ...`.
  In Chroma mode it's a no-op for the vector index; transactions are handled by
  the meta store (SQLite today, Postgres later).
"""

from contextlib import asynccontextmanager, contextmanager
from dataclasses import dataclass
from typing import Any, AsyncIterator, Dict, Iterator, Protocol

JSONDict = Dict[str, Any]


class UnitOfWork(Protocol):
    @contextmanager
    def transaction(self) -> Iterator[None]: ...


class AsyncUnitOfWork(Protocol):
    @asynccontextmanager
    async def transaction(self) -> AsyncIterator[None]: ...


@dataclass
class NoopUnitOfWork(UnitOfWork):
    @contextmanager
    def transaction(self) -> Iterator[None]:
        yield


@dataclass
class AsyncNoopUnitOfWork(AsyncUnitOfWork):
    @asynccontextmanager
    async def transaction(self) -> AsyncIterator[None]:
        yield


class StorageBackend(Protocol):
    # Generic dispatch (optional to use directly)
    def call(self, collection_key: str, method: str, **kwargs) -> Any: ...

    # Node index (optional)
    def node_index_get(self, **kwargs) -> Any: ...
    def node_index_query(self, **kwargs) -> Any: ...
    def node_index_add(self, **kwargs) -> Any: ...
    def node_index_upsert(self, **kwargs) -> Any: ...
    def node_index_update(self, **kwargs) -> Any: ...
    def node_index_delete(self, **kwargs) -> Any: ...

    # Nodes
    def node_get(self, **kwargs) -> Any: ...
    def node_query(self, **kwargs) -> Any: ...
    def node_add(self, **kwargs) -> Any: ...
    def node_upsert(self, **kwargs) -> Any: ...
    def node_update(self, **kwargs) -> Any: ...
    def node_delete(self, **kwargs) -> Any: ...

    # Edges
    def edge_get(self, **kwargs) -> Any: ...
    def edge_query(self, **kwargs) -> Any: ...
    def edge_add(self, **kwargs) -> Any: ...
    def edge_upsert(self, **kwargs) -> Any: ...
    def edge_update(self, **kwargs) -> Any: ...
    def edge_delete(self, **kwargs) -> Any: ...

    # Edge endpoints (hypergraph incidence/materialization)
    def edge_endpoints_get(self, **kwargs) -> Any: ...
    def edge_endpoints_query(self, **kwargs) -> Any: ...
    def edge_endpoints_add(self, **kwargs) -> Any: ...
    def edge_endpoints_upsert(self, **kwargs) -> Any: ...
    def edge_endpoints_update(self, **kwargs) -> Any: ...
    def edge_endpoints_delete(self, **kwargs) -> Any: ...

    # Documents
    def document_get(self, **kwargs) -> Any: ...
    def document_query(self, **kwargs) -> Any: ...
    def document_add(self, **kwargs) -> Any: ...
    def document_upsert(self, **kwargs) -> Any: ...
    def document_update(self, **kwargs) -> Any: ...
    def document_delete(self, **kwargs) -> Any: ...

    # Domains
    def domain_get(self, **kwargs) -> Any: ...
    def domain_query(self, **kwargs) -> Any: ...
    def domain_add(self, **kwargs) -> Any: ...
    def domain_upsert(self, **kwargs) -> Any: ...
    def domain_update(self, **kwargs) -> Any: ...
    def domain_delete(self, **kwargs) -> Any: ...

    # Node docs
    def node_docs_get(self, **kwargs) -> Any: ...
    def node_docs_query(self, **kwargs) -> Any: ...
    def node_docs_add(self, **kwargs) -> Any: ...
    def node_docs_upsert(self, **kwargs) -> Any: ...
    def node_docs_update(self, **kwargs) -> Any: ...
    def node_docs_delete(self, **kwargs) -> Any: ...

    # Node refs
    def node_refs_get(self, **kwargs) -> Any: ...
    def node_refs_query(self, **kwargs) -> Any: ...
    def node_refs_add(self, **kwargs) -> Any: ...
    def node_refs_upsert(self, **kwargs) -> Any: ...
    def node_refs_update(self, **kwargs) -> Any: ...
    def node_refs_delete(self, **kwargs) -> Any: ...

    # Edge refs
    def edge_refs_get(self, **kwargs) -> Any: ...
    def edge_refs_query(self, **kwargs) -> Any: ...
    def edge_refs_add(self, **kwargs) -> Any: ...
    def edge_refs_upsert(self, **kwargs) -> Any: ...
    def edge_refs_update(self, **kwargs) -> Any: ...
    def edge_refs_delete(self, **kwargs) -> Any: ...
