import json
import os
import sys
from pathlib import Path

# Add the project root to sys.path to allow importing kogwistar
sys.path.append(str(Path(__file__).parent.parent))

from kogwistar.runtime.models import (
    WorkflowNodeMetadata,
    WorkflowEdgeMetadata,
)
from pydantic_extension.model_slicing import use_mode


def export_schemas():
    # Use environment variable or default to a relative path from the script repo
    env_path = os.getenv("FRONTEND_SRC_PATH")
    if env_path:
        frontend_src = Path(env_path)
    else:
        # Relative path from: /parent/graphrag_v2_working_tree/scripts/export_schemas.py
        # to: /parent/kogwistar/designer-app-source/src
        frontend_src = (
            Path(__file__).resolve().parent.parent.parent.parent
            / "kogwistar"
            / "designer-app-source"
            / "src"
        )

    if not frontend_src.exists():
        print(f"⚠️ Error: Frontend path {frontend_src} does not exist.")
        print("Please set the FRONTEND_SRC_PATH environment variable.")
        return

    generated_dir = frontend_src / "generated"
    generated_dir.mkdir(exist_ok=True)

    schemas = {}

    # Export using the 'frontend' slice/mode
    with use_mode("frontend"):
        schemas["WorkflowNodeMetadata"] = WorkflowNodeMetadata.model_json_schema()
        schemas["WorkflowEdgeMetadata"] = WorkflowEdgeMetadata.model_json_schema()

    output_path = generated_dir / "schemas.json"
    with open(output_path, "w") as f:
        json.dump(schemas, f, indent=2)

    print(f"✅ Exported {len(schemas)} schemas to {output_path}")

    # Also generate a simple TS helper to import these
    ts_helper = generated_dir / "schemas.ts"
    with open(ts_helper, "w") as f:
        f.write("// Automatically generated by scripts/export_schemas.py\n")
        f.write("import schemasJson from './schemas.json';\n\n")
        f.write("export const schemas = schemasJson as const;\n")
        f.write("export type SchemaName = keyof typeof schemas;\n")

    print(f"✅ Generated TS helper: {ts_helper}")


if __name__ == "__main__":
    export_schemas()
